blueprint:
  name: YAIC Person Snapshot to MQTT + Notify (2024.8+)
  description: >-
    On person event: take snapshot, publish to YAIC MQTT, send notification.
  domain: automation
  input:
    trigger_event_entity:
      name: Event Entity
      selector:
        entity:
          domain: event

    trigger_cmd:
      name: Command Filter
      default: ipc_human
      selector:
        text: {}

    camera_entity:
      name: Camera Entity
      selector:
        entity:
          domain: camera

    source_id:
      name: YAIC Source ID
      selector:
        text: {}

    snapshot_path:
      name: Snapshot File Path
      default: /config/www/yaic_latest.jpg
      selector:
        text: {}

    mqtt_topic_base:
      name: MQTT Topic Base
      default: yaic/input
      selector:
        text: {}

    notification_title:
      name: Notification Title
      default: YAIC
      selector:
        text: {}

    notification_message:
      name: Notification Message
      default: Human body detected
      selector:
        text: {}

    notification_image:
      name: Notification Image URL
      default: ''
      selector:
        text: {}

    notify_action:
      name: Notify Action
      description: >-
        Notification action. You can use {{ _notify_title }}, {{ _notify_message }},
        and {{ _notify_image }} in the action data.
      selector:
        action: {}

mode: queued
max: 5

variables:
  _snapshot_path: !input snapshot_path
  _source_id: !input source_id
  _mqtt_base: !input mqtt_topic_base
  _notify_title: !input notification_title
  _notify_message: !input notification_message
  _custom_image: !input notification_image

  _message_json: >-
    {{
      (
        trigger.event.data.new_state.attributes.message
        if trigger.event.data.new_state
        and trigger.event.data.new_state.attributes.message is defined
        else '{}'
      ) | from_json
    }}

  _notify_image: >-
    {% if _custom_image | trim %}
      {{ _custom_image }}
    {% elif _snapshot_path.startswith('/config/www/') %}
      {{ '/local/' ~ _snapshot_path[13:] }}
    {% else %}
      {{ '' }}
    {% endif %}

trigger:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: !input trigger_event_entity

condition:
  - condition: template
    value_template: "{{ _message_json.get('cmd') == trigger_cmd }}"

action:
  - action: camera.snapshot
    data:
      entity_id: !input camera_entity
      filename: '{{ _snapshot_path }}'

  - service: mqtt.publish
    data:
      topic: "{{ _mqtt_base.rstrip('/') ~ '/' ~ _source_id ~ '/image' }}"
      qos: 1
      retain: false
      payload_json:
        image_b64: '{{ readfile(_snapshot_path) | b64encode }}'
        device: '{{ _source_id }}'

  - !input notify_action
