blueprint:
  name: YAIC Person Snapshot to MQTT + Notify
  description: >-
    When a camera event indicates a person, take a snapshot, publish it to YAIC
    MQTT input, then send a notification.
  domain: automation
  input:
    trigger_event_entity:
      name: Event Entity
      description: Event entity that fires with a JSON message payload.
      selector:
        entity:
          domain: event
    trigger_cmd:
      name: Command Filter
      description: Only continue when the event message JSON has this cmd.
      default: ipc_human
      selector:
        text: {}
    camera_entity:
      name: Camera Entity
      selector:
        entity:
          domain: camera
    source_id:
      name: YAIC Source ID
      description: Used in the MQTT topic yaic/input/<source_id>/image.
      selector:
        text: {}
    snapshot_path:
      name: Snapshot File Path
      description: Path for camera.snapshot (should be under /config/www/ for /local access).
      default: /config/www/yaic_latest.jpg
      selector:
        text: {}
    mqtt_topic_base:
      name: MQTT Topic Base
      description: Base MQTT topic for YAIC input.
      default: yaic/input
      selector:
        text: {}
    notification_message:
      name: Notification Message
      default: Human Body detected
      selector:
        text: {}
    notification_title:
      name: Notification Title
      default: YAIC
      selector:
        text: {}
    notification_image:
      name: Notification Image URL
      description: Optional /local/... URL. Leave blank to derive from snapshot_path.
      default: ""
      selector:
        text: {}
    notify_action:
      name: Notify Action
      description: >-
        Notification action. You can use {{ _notify_title }}, {{ _notify_message }},
        and {{ _notify_image }} in the action data.
      selector:
        action: {}

mode: single

variables:
  _message_json: >-
    {{ trigger.to_state.attributes.message | default('{}') | from_json }}
  _snapshot_path: !input snapshot_path
  _notify_title: !input notification_title
  _notify_message: !input notification_message
  _notify_image: >-
    {% set custom = (notification_image | string).strip() %}
    {% if custom %}
      {{ custom }}
    {% elif _snapshot_path.startswith('/config/www/') %}
      {{ '/local/' ~ _snapshot_path[13:] }}
    {% else %}
      {{ '' }}
    {% endif %}

trigger:
  - platform: state
    entity_id: !input trigger_event_entity

condition:
  - condition: template
    value_template: >-
      {{ _message_json.cmd == (trigger_cmd | string) }}

action:
  - service: camera.snapshot
    data:
      entity_id: !input camera_entity
      filename: !input snapshot_path

  - service: mqtt.publish
    data:
      topic: >-
        {{ (mqtt_topic_base | string).rstrip('/') ~ '/' ~ (source_id | string) ~ '/image' }}
      payload: >-
        {{ '{"image_b64": "' ~ (readfile(_snapshot_path) | b64encode | string) ~ '", "device": "' ~ (source_id | string) ~ '"}' }}

  - !input notify_action
